[2022-06-03 19:10:28,726] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T19:07:40.871954+00:00 [queued]>
[2022-06-03 19:10:28,736] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T19:07:40.871954+00:00 [queued]>
[2022-06-03 19:10:28,737] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 19:10:28,737] {taskinstance.py:1358} INFO - Starting attempt 2 of 2
[2022-06-03 19:10:28,738] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 19:10:28,752] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): send_email_report> on 2022-06-03 19:07:40.871954+00:00
[2022-06-03 19:10:28,757] {standard_task_runner.py:52} INFO - Started process 320 to run task
[2022-06-03 19:10:28,760] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'send_email_report', 'manual__2022-06-03T19:07:40.871954+00:00', '--job-id', '326', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmpmw_qhyz7', '--error-file', '/tmp/tmp33x_uc_q']
[2022-06-03 19:10:28,761] {standard_task_runner.py:80} INFO - Job 326: Subtask send_email_report
[2022-06-03 19:10:28,817] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T19:07:40.871954+00:00 [running]> on host 6f91192a153c
[2022-06-03 19:10:29,049] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=send_email_report
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T19:07:40.871954+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-03T19:07:40.871954+00:00
[2022-06-03 19:10:29,460] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-06-03 19:10:29,461] {email.py:228} INFO - Email alerting: attempt 1
[2022-06-03 19:10:59,565] {email.py:228} INFO - Email alerting: attempt 2
[2022-06-03 19:11:29,653] {email.py:228} INFO - Email alerting: attempt 3
[2022-06-03 19:11:59,753] {email.py:228} INFO - Email alerting: attempt 4
[2022-06-03 19:12:29,853] {email.py:228} INFO - Email alerting: attempt 5
[2022-06-03 19:12:59,973] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/smtplib.py", line 392, in getreply
    line = self.file.readline(_MAXLINE + 1)
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etls/email_reports.py", line 12, in email_callback
    html_content=quality_report(df),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 338, in connect
    (code, msg) = self.getreply()
  File "/usr/local/lib/python3.7/smtplib.py", line 396, in getreply
    + str(e))
smtplib.SMTPServerDisconnected: Connection unexpectedly closed: timed out
[2022-06-03 19:12:59,993] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=nyc_bus_breakdown_pipeline, task_id=send_email_report, execution_date=20220603T190740, start_date=20220603T191028, end_date=20220603T191259
[2022-06-03 19:13:00,011] {standard_task_runner.py:97} ERROR - Failed to execute job 326 for task send_email_report (Connection unexpectedly closed: timed out; 320)
[2022-06-03 19:13:00,033] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-03 19:13:00,060] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
