[2022-06-03 18:48:44,710] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T18:48:29.446947+00:00 [queued]>
[2022-06-03 18:48:44,719] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T18:48:29.446947+00:00 [queued]>
[2022-06-03 18:48:44,720] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 18:48:44,721] {taskinstance.py:1358} INFO - Starting attempt 2 of 2
[2022-06-03 18:48:44,721] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 18:48:44,736] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): send_email_report> on 2022-06-03 18:48:29.446947+00:00
[2022-06-03 18:48:44,741] {standard_task_runner.py:52} INFO - Started process 170 to run task
[2022-06-03 18:48:44,744] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'send_email_report', 'manual__2022-06-03T18:48:29.446947+00:00', '--job-id', '308', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmp289w6b_o', '--error-file', '/tmp/tmp13fxkfhz']
[2022-06-03 18:48:44,745] {standard_task_runner.py:80} INFO - Job 308: Subtask send_email_report
[2022-06-03 18:48:44,799] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T18:48:29.446947+00:00 [running]> on host 9386241ecd4e
[2022-06-03 18:48:45,016] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=send_email_report
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T18:48:29.446947+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-03T18:48:29.446947+00:00
[2022-06-03 18:48:45,464] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-06-03 18:48:45,465] {email.py:228} INFO - Email alerting: attempt 1
[2022-06-03 18:48:45,848] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etls/email_reports.py", line 12, in email_callback
    html_content=quality_report(df),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 239, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/lib/python3.7/smtplib.py", line 735, in login
    raise last_exception
  File "/usr/local/lib/python3.7/smtplib.py", line 726, in login
    initial_response_ok=initial_response_ok)
  File "/usr/local/lib/python3.7/smtplib.py", line 647, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials t6-20020a05620a450600b006a6a46db013sm1163367qkp.95 - gsmtp')
[2022-06-03 18:48:45,862] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=nyc_bus_breakdown_pipeline, task_id=send_email_report, execution_date=20220603T184829, start_date=20220603T184844, end_date=20220603T184845
[2022-06-03 18:48:45,872] {standard_task_runner.py:97} ERROR - Failed to execute job 308 for task send_email_report ((535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials t6-20020a05620a450600b006a6a46db013sm1163367qkp.95 - gsmtp'); 170)
[2022-06-03 18:48:45,882] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-03 18:48:45,930] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
