[2022-06-02 21:53:24,317] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T21:53:09.353408+00:00 [queued]>
[2022-06-02 21:53:24,329] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T21:53:09.353408+00:00 [queued]>
[2022-06-02 21:53:24,330] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 21:53:24,331] {taskinstance.py:1358} INFO - Starting attempt 2 of 2
[2022-06-02 21:53:24,331] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 21:53:24,346] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): processing_data> on 2022-06-02 21:53:09.353408+00:00
[2022-06-02 21:53:24,350] {standard_task_runner.py:52} INFO - Started process 238 to run task
[2022-06-02 21:53:24,354] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'processing_data', 'manual__2022-06-02T21:53:09.353408+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmp64do94m9', '--error-file', '/tmp/tmpwy97_qbr']
[2022-06-02 21:53:24,356] {standard_task_runner.py:80} INFO - Job 51: Subtask processing_data
[2022-06-02 21:53:24,419] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T21:53:09.353408+00:00 [running]> on host 2ac97db4f2c6
[2022-06-02 21:53:24,504] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T21:53:09.353408+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-02T21:53:09.353408+00:00
[2022-06-02 21:53:25,179] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etls/transformations.py", line 85, in processing_data
    hook.load_file(filename=df.to_hdf(key), key=key, bucket_name=bucket_name)
TypeError: to_hdf() missing 1 required positional argument: 'key'
[2022-06-02 21:53:25,194] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=nyc_bus_breakdown_pipeline, task_id=processing_data, execution_date=20220602T215309, start_date=20220602T215324, end_date=20220602T215325
[2022-06-02 21:53:25,210] {standard_task_runner.py:97} ERROR - Failed to execute job 51 for task processing_data (to_hdf() missing 1 required positional argument: 'key'; 238)
[2022-06-02 21:53:25,249] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-02 21:53:25,284] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
