[2022-06-03 16:21:19,564] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.create_table manual__2022-06-03T16:21:16.955922+00:00 [queued]>
[2022-06-03 16:21:19,586] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.create_table manual__2022-06-03T16:21:16.955922+00:00 [queued]>
[2022-06-03 16:21:19,588] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 16:21:19,590] {taskinstance.py:1358} INFO - Starting attempt 1 of 2
[2022-06-03 16:21:19,590] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 16:21:19,620] {taskinstance.py:1378} INFO - Executing <Task(MsSqlOperator): create_table> on 2022-06-03 16:21:16.955922+00:00
[2022-06-03 16:21:19,637] {standard_task_runner.py:52} INFO - Started process 143 to run task
[2022-06-03 16:21:19,643] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'create_table', 'manual__2022-06-03T16:21:16.955922+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmp4dspixg4', '--error-file', '/tmp/tmprrj9mc1i']
[2022-06-03 16:21:19,645] {standard_task_runner.py:80} INFO - Job 134: Subtask create_table
[2022-06-03 16:21:19,757] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.create_table manual__2022-06-03T16:21:16.955922+00:00 [running]> on host 6cc5764fb927
[2022-06-03 16:21:20,297] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T16:21:16.955922+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-03T16:21:16.955922+00:00
[2022-06-03 16:21:20,299] {mssql.py:92} INFO - Executing: CREATE TABLE testdb.dbo.pet (name VARCHAR(20), owner VARCHAR(20));
[2022-06-03 16:21:20,331] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/mssql/operators/mssql.py", line 93, in execute
    hook = self.get_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/microsoft/mssql/operators/mssql.py", line 83, in get_hook
    conn = MsSqlHook.get_connection(conn_id=self.mssql_conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mssql_default` isn't defined
[2022-06-03 16:21:20,338] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_bus_breakdown_pipeline, task_id=create_table, execution_date=20220603T162116, start_date=20220603T162119, end_date=20220603T162120
[2022-06-03 16:21:20,360] {standard_task_runner.py:97} ERROR - Failed to execute job 134 for task create_table (The conn_id `mssql_default` isn't defined; 143)
[2022-06-03 16:21:20,385] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-03 16:21:20,441] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
