[2022-06-02 23:23:39,239] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T23:23:28.014039+00:00 [queued]>
[2022-06-02 23:23:39,249] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T23:23:28.014039+00:00 [queued]>
[2022-06-02 23:23:39,250] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 23:23:39,250] {taskinstance.py:1358} INFO - Starting attempt 2 of 2
[2022-06-02 23:23:39,251] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 23:23:39,267] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): processing_data> on 2022-06-02 23:23:28.014039+00:00
[2022-06-02 23:23:39,272] {standard_task_runner.py:52} INFO - Started process 1001 to run task
[2022-06-02 23:23:39,276] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'processing_data', 'manual__2022-06-02T23:23:28.014039+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmpwi8b9ipw', '--error-file', '/tmp/tmp1fzs24xh']
[2022-06-02 23:23:39,277] {standard_task_runner.py:80} INFO - Job 101: Subtask processing_data
[2022-06-02 23:23:39,335] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T23:23:28.014039+00:00 [running]> on host 8e84f5cf889f
[2022-06-02 23:23:39,413] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T23:23:28.014039+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-02T23:23:28.014039+00:00
[2022-06-02 23:23:40,203] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etls/transformations.py", line 85, in processing_data
    hook.load_string(string_data=df.to_csv(name), key=name, bucket_name=bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 650, in load_string
    bytes_data = string_data.encode(encoding)
AttributeError: 'NoneType' object has no attribute 'encode'
[2022-06-02 23:23:40,218] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=nyc_bus_breakdown_pipeline, task_id=processing_data, execution_date=20220602T232328, start_date=20220602T232339, end_date=20220602T232340
[2022-06-02 23:23:40,230] {standard_task_runner.py:97} ERROR - Failed to execute job 101 for task processing_data ('NoneType' object has no attribute 'encode'; 1001)
[2022-06-02 23:23:40,251] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-02 23:23:40,282] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
