[2022-06-02 23:20:23,166] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T23:20:18.798664+00:00 [queued]>
[2022-06-02 23:20:23,175] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T23:20:18.798664+00:00 [queued]>
[2022-06-02 23:20:23,176] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 23:20:23,176] {taskinstance.py:1358} INFO - Starting attempt 1 of 2
[2022-06-02 23:20:23,177] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-02 23:20:23,210] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): processing_data> on 2022-06-02 23:20:18.798664+00:00
[2022-06-02 23:20:23,217] {standard_task_runner.py:52} INFO - Started process 763 to run task
[2022-06-02 23:20:23,220] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'processing_data', 'manual__2022-06-02T23:20:18.798664+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmp_z78hnhk', '--error-file', '/tmp/tmpp2egj_sl']
[2022-06-02 23:20:23,222] {standard_task_runner.py:80} INFO - Job 94: Subtask processing_data
[2022-06-02 23:20:23,278] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.processing_data manual__2022-06-02T23:20:18.798664+00:00 [running]> on host 8e84f5cf889f
[2022-06-02 23:20:23,452] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=processing_data
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T23:20:18.798664+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-02T23:20:18.798664+00:00
[2022-06-02 23:20:24,595] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etls/transformations.py", line 85, in processing_data
    hook.load_string(string_data=df.to_hdf(name, key="df", mode='a', format="table"), key=name, bucket_name=bucket_name)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 63, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 91, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 650, in load_string
    bytes_data = string_data.encode(encoding)
AttributeError: 'NoneType' object has no attribute 'encode'
[2022-06-02 23:20:24,608] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_bus_breakdown_pipeline, task_id=processing_data, execution_date=20220602T232018, start_date=20220602T232023, end_date=20220602T232024
[2022-06-02 23:20:24,620] {standard_task_runner.py:97} ERROR - Failed to execute job 94 for task processing_data ('NoneType' object has no attribute 'encode'; 763)
[2022-06-02 23:20:24,640] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-02 23:20:24,672] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
