[2022-06-03 18:36:07,240] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T18:35:51.521068+00:00 [queued]>
[2022-06-03 18:36:07,251] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T18:35:51.521068+00:00 [queued]>
[2022-06-03 18:36:07,251] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 18:36:07,252] {taskinstance.py:1358} INFO - Starting attempt 2 of 2
[2022-06-03 18:36:07,253] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 18:36:07,270] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): send_email_report> on 2022-06-03 18:35:51.521068+00:00
[2022-06-03 18:36:07,275] {standard_task_runner.py:52} INFO - Started process 218 to run task
[2022-06-03 18:36:07,279] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'send_email_report', 'manual__2022-06-03T18:35:51.521068+00:00', '--job-id', '212', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmp4r9kcpr7', '--error-file', '/tmp/tmpf700lqsw']
[2022-06-03 18:36:07,280] {standard_task_runner.py:80} INFO - Job 212: Subtask send_email_report
[2022-06-03 18:36:07,342] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T18:35:51.521068+00:00 [running]> on host 460a606642e9
[2022-06-03 18:36:07,549] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=send_email_report
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T18:35:51.521068+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-03T18:35:51.521068+00:00
[2022-06-03 18:36:08,070] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-06-03 18:36:08,070] {configuration.py:549} WARNING - section/key [smtp/smtp_user] not found in config
[2022-06-03 18:36:08,070] {email.py:228} INFO - Email alerting: attempt 1
[2022-06-03 18:36:08,071] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etls/email_reports.py", line 12, in email_callback
    html_content=quality_report(df),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 230, in send_mime_email
    smtp_conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 264, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2022-06-03 18:36:08,085] {taskinstance.py:1401} INFO - Marking task as FAILED. dag_id=nyc_bus_breakdown_pipeline, task_id=send_email_report, execution_date=20220603T183551, start_date=20220603T183607, end_date=20220603T183608
[2022-06-03 18:36:08,098] {standard_task_runner.py:97} ERROR - Failed to execute job 212 for task send_email_report ([Errno 99] Cannot assign requested address; 218)
[2022-06-03 18:36:08,134] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-03 18:36:08,166] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
