[2022-06-03 19:03:52,832] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T19:03:45.938646+00:00 [queued]>
[2022-06-03 19:03:52,845] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T19:03:45.938646+00:00 [queued]>
[2022-06-03 19:03:52,846] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 19:03:52,847] {taskinstance.py:1358} INFO - Starting attempt 1 of 2
[2022-06-03 19:03:52,847] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-03 19:03:52,862] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): send_email_report> on 2022-06-03 19:03:45.938646+00:00
[2022-06-03 19:03:52,868] {standard_task_runner.py:52} INFO - Started process 172 to run task
[2022-06-03 19:03:52,871] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'nyc_bus_breakdown_pipeline', 'send_email_report', 'manual__2022-06-03T19:03:45.938646+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/nycbus_etl.py', '--cfg-path', '/tmp/tmpz8d5mzb7', '--error-file', '/tmp/tmp16pshc0h']
[2022-06-03 19:03:52,872] {standard_task_runner.py:80} INFO - Job 318: Subtask send_email_report
[2022-06-03 19:03:52,937] {task_command.py:370} INFO - Running <TaskInstance: nyc_bus_breakdown_pipeline.send_email_report manual__2022-06-03T19:03:45.938646+00:00 [running]> on host c770104e2714
[2022-06-03 19:03:53,203] {taskinstance.py:1572} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=nyc_bus_breakdown_pipeline
AIRFLOW_CTX_TASK_ID=send_email_report
AIRFLOW_CTX_EXECUTION_DATE=2022-06-03T19:03:45.938646+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-03T19:03:45.938646+00:00
[2022-06-03 19:03:53,845] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/email.py:119: PendingDeprecationWarning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
  send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)

[2022-06-03 19:03:53,845] {email.py:228} INFO - Email alerting: attempt 1
[2022-06-03 19:03:54,175] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etls/email_reports.py", line 12, in email_callback
    html_content=quality_report(df),
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 71, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 119, in send_email_smtp
    send_mime_email(e_from=mail_from, e_to=recipients, mime_msg=msg, conn_id=conn_id, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/email.py", line 239, in send_mime_email
    smtp_conn.login(smtp_user, smtp_password)
  File "/usr/local/lib/python3.7/smtplib.py", line 726, in login
    initial_response_ok=initial_response_ok)
  File "/usr/local/lib/python3.7/smtplib.py", line 636, in auth
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)
  File "/usr/local/lib/python3.7/smtplib.py", line 426, in docmd
    return self.getreply()
  File "/usr/local/lib/python3.7/smtplib.py", line 399, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
[2022-06-03 19:03:54,190] {taskinstance.py:1401} INFO - Marking task as UP_FOR_RETRY. dag_id=nyc_bus_breakdown_pipeline, task_id=send_email_report, execution_date=20220603T190345, start_date=20220603T190352, end_date=20220603T190354
[2022-06-03 19:03:54,203] {standard_task_runner.py:97} ERROR - Failed to execute job 318 for task send_email_report (Connection unexpectedly closed; 172)
[2022-06-03 19:03:54,249] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-03 19:03:54,284] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
